Repository debarshee2004/hr_management_app, pull requests merged in 2024-01, with the labels that each got.

#1 loading page added
  .expo/README.md
  .expo/devices.json
  App.js
  assets/app_logo/logo.svg
  src/screens/Loading.jsx
Labels: medium, apertre

#2 Font and Intro Screen Added
  .gitignore
  App.js
  assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
  assets/fonts/Montserrat-VariableFont_wght.ttf
  assets/fonts/OFL.txt
  assets/fonts/README.txt
  assets/fonts/static/Montserrat-Black.ttf
  assets/fonts/static/Montserrat-BlackItalic.ttf
  assets/fonts/static/Montserrat-Bold.ttf
  assets/fonts/static/Montserrat-BoldItalic.ttf
  assets/fonts/static/Montserrat-ExtraBold.ttf
  assets/fonts/static/Montserrat-ExtraBoldItalic.ttf
  assets/fonts/static/Montserrat-ExtraLight.ttf
  assets/fonts/static/Montserrat-ExtraLightItalic.ttf
  assets/fonts/static/Montserrat-Italic.ttf
  assets/fonts/static/Montserrat-Light.ttf
  assets/fonts/static/Montserrat-LightItalic.ttf
  assets/fonts/static/Montserrat-Medium.ttf
  assets/fonts/static/Montserrat-MediumItalic.ttf
  assets/fonts/static/Montserrat-Regular.ttf
  assets/fonts/static/Montserrat-SemiBold.ttf
  assets/fonts/static/Montserrat-SemiBoldItalic.ttf
  assets/fonts/static/Montserrat-Thin.ttf
  assets/fonts/static/Montserrat-ThinItalic.ttf
  assets/mockups/Frame1.jsx
  assets/mockups/Frame2.jsx
  assets/mockups/Frame3.jsx
  metro.config.js
  package-lock.json
  package.json
  src/components/IntroItems.jsx
  src/screens/IntroScreen.jsx
  src/screens/Loading.jsx
Labels: apertre, hard, exceptional

#3 Welcome screen added
  App.js
  src/screens/Welcome.jsx
Labels: medium, apertre

#11 Update README.md
  README.md
Labels: documentation, apertre, easy

#8 Signup Screen added
  App.js
  src/screens/SignupScreen.jsx
Labels: medium, apertre
